I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 456, in script
    python hide:
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 456, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 456, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 466, in _execute_python_hide
    renpy.load("_reload-2")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\main.py", line 143, in run
    renpy.execution.run_context(True)
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\execution.py", line 908, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 456, in script
    python hide:
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 456, in script
    python hide:
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 456, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 466, in _execute_python_hide
    renpy.load("_reload-2")
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\loadsave.py", line 770, in load
    log.unfreeze(roots, label="_after_load")
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 1983, in unfreeze
    self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 1815, in rollback
    self.load_failed()
  File "C:\Users\suriv\Downloads\My Things\IMPORTANT\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 1733, in load_failed
    raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Passion Fruits - Demo 1.0
Fri Jun 16 18:45:09 2023
